# SetUp & LoadDataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/sample_data/pneumonia_dataset.csv')
df

,PatientID,Gender,Age,Cough,Fever,Shortness_of_breath,Chest_pain,Fatigue,Confusion,Oxygen_saturation,Crackles,Xray,WBC_count,Sputum_color,Temperature,Diagnosis
0,PNEU4091,M,3,Bloody,High,Mild,Mild,NaN,No,92,Yes,-,-,-,39.7,Yes
1,PNEU6231,M,3,Dry,NaN,NaN,NaN,Mild,-,-,Yes,-,-,Clear,37.0,No
2,PNEU6486,M,3,Dry,NaN,NaN,NaN,Mild,No,99,No,-,-,-,38.0,No
3,PNEU7601,F,3,NaN,Low,Severe,NaN,Moderate,No,99,Yes,-,-,Clear,40.9,Yes
4,PNEU8471,F,3,NaN,High,Moderate,Severe,Mild,-,91,No,-,-,Green,38.1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,PNEU360,F,90,Wet,NaN,Moderate,Moderate,Moderate,No,99,Yes,-,-,Green,38.3,Yes
706,PNEU4391,F,90,Dry,High,Moderate,Moderate,Moderate,Yes,91,Yes,-,-,Bloody,37.2,Yes
707,PNEU6720,M,90,Dry,NaN,NaN,NaN,Mild,No,90,Yes,-,-,-,37.0,No
708,PNEU9254,M,90,NaN,Moderate,Severe,Severe,Moderate,No,93,Yes,-,-,Bloody,36.2,Yes
709,PNEU9397,F,90,NaN,NaN,Mild,Mild,Mild,No,92,No,-,-,Clear,40.0,No

# 1.Basic Informations

**About rows,columns, dataTypes**

## shape

In [3]:
print("Shape : ",df.shape)

Shape :  (710, 16)

## information

In [4]:
print("Informarions : ",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PatientID            710 non-null    object
 1   Gender               710 non-null    object
 2   Age                  710 non-null    int64
 3   Cough                398 non-null    object
 4   Fever                400 non-null    object
 5   Shortness_of_breath  393 non-null    object
 6   Chest_pain           367 non-null    object
 7   Fatigue              605 non-null    object
 8   Confusion            710 non-null    object
 9   Oxygen_saturation    710 non-null    object
 10  Crackles             710 non-null    object
 11  Xray                 710 non-null    object
 12  WBC_count            710 non-null    object
 13  Sputum_color         710 non-null    object
 14  Temperature          710 non-null    float64
 15  Diagnosis            710 non-null    object
dtypes: float64(1), int64(1), object(14)
memory usage: 88.9+ KB
Informarions :  None

## unique

In [5]:
df.nunique()

PatientID              687
Gender                   2
Age                     88
Cough                    3
Fever                    3
Shortness_of_breath      3
Chest_pain               3
Fatigue                  3
Confusion                3
Oxygen_saturation       17
Crackles                 2
Xray                     5
WBC_count               11
Sputum_color             5
Temperature             54
Diagnosis                2
dtype: int64

In [6]:
df.columns

Index(['PatientID', 'Gender', 'Age', 'Cough', 'Fever', 'Shortness_of_breath',
       'Chest_pain', 'Fatigue', 'Confusion', 'Oxygen_saturation', 'Crackles',
       'Xray', 'WBC_count', 'Sputum_color', 'Temperature', 'Diagnosis'],
      dtype='object')

> Insight: At this point you should know basic things like how many rows and columns you have, what each column type is, and whether there are any suspicious values such as negative ages or impossible measurements.

# 2.Handling Missing Values

In [7]:
df.isna().sum()

PatientID                0
Gender                   0
Age                      0
Cough                  312
Fever                  310
Shortness_of_breath    317
Chest_pain             343
Fatigue                105
Confusion                0
Oxygen_saturation        0
Crackles                 0
Xray                     0
WBC_count                0
Sputum_color             0
Temperature              0
Diagnosis                0
dtype: int64

In [8]:
missing_cols = ['Cough', 'Fever', 'Shortness_of_breath', 'Chest_pain', 'Fatigue']
missing_cols

['Cough', 'Fever', 'Shortness_of_breath', 'Chest_pain', 'Fatigue']

## Import libraries

In [9]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [ ]:
#Numerical Pipeline

#There is no missing value in numeric column so
#Numeric pipeline no needed.

In [10]:
from sklearn import preprocessing
# Catg pipeline

cat_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent'))
])

In [11]:
#column Transformation

preprocessor = ColumnTransformer(
    transformers=[
        ('ordinal_col',cat_pipeline,missing_cols)
    ],
    remainder='passthrough'
)

In [12]:
preprocessor.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal_col',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Cough', 'Fever', 'Shortness_of_breath',
                                  'Chest_pain', 'Fatigue'])])

In [13]:
df_clean = preprocessor.fit_transform(df)
df_clean

,ordinal_col__Cough,ordinal_col__Fever,ordinal_col__Shortness_of_breath,ordinal_col__Chest_pain,ordinal_col__Fatigue,remainder__PatientID,remainder__Gender,remainder__Age,remainder__Confusion,remainder__Oxygen_saturation,remainder__Crackles,remainder__Xray,remainder__WBC_count,remainder__Sputum_color,remainder__Temperature,remainder__Diagnosis
0,Bloody,High,Mild,Mild,Mild,PNEU4091,M,3,No,92,Yes,-,-,-,39.7,Yes
1,Dry,Low,Mild,Mild,Mild,PNEU6231,M,3,-,-,Yes,-,-,Clear,37.0,No
2,Dry,Low,Mild,Mild,Mild,PNEU6486,M,3,No,99,No,-,-,-,38.0,No
3,Dry,Low,Severe,Mild,Moderate,PNEU7601,F,3,No,99,Yes,-,-,Clear,40.9,Yes
4,Dry,High,Moderate,Severe,Mild,PNEU8471,F,3,-,91,No,-,-,Green,38.1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,Wet,Low,Moderate,Moderate,Moderate,PNEU360,F,90,No,99,Yes,-,-,Green,38.3,Yes
706,Dry,High,Moderate,Moderate,Moderate,PNEU4391,F,90,Yes,91,Yes,-,-,Bloody,37.2,Yes
707,Dry,Low,Mild,Mild,Mild,PNEU6720,M,90,No,90,Yes,-,-,-,37.0,No
708,Dry,Moderate,Severe,Severe,Moderate,PNEU9254,M,90,No,93,Yes,-,-,Bloody,36.2,Yes
709,Dry,Low,Mild,Mild,Mild,PNEU9397,F,90,No,92,No,-,-,Clear,40.0,No

In [14]:
df_clean.isna().sum()

ordinal_col__Cough                  0
ordinal_col__Fever                  0
ordinal_col__Shortness_of_breath    0
ordinal_col__Chest_pain             0
ordinal_col__Fatigue                0
remainder__PatientID                0
remainder__Gender                   0
remainder__Age                      0
remainder__Confusion                0
remainder__Oxygen_saturation        0
remainder__Crackles                 0
remainder__Xray                     0
remainder__WBC_count                0
remainder__Sputum_color             0
remainder__Temperature              0
remainder__Diagnosis                0
dtype: int64